== はじめに

=== 本講義の目的・内容

本講義(計3回)の目的は，クラウドの初心者を対象とし，クラウドの基礎的な知識・概念を解説する．また，
Amazon Web Service (AWS)の提供するクラウド環境を実例として，具体的なクラウドの利用方法をハンズオンを通して学ぶ．

特に，科学・エンジニアリングの学生を対象として，研究などの目的でクラウドを利用するための実践的な手順を紹介する．知識・理論の説明は最小限に留め，実践を行う中で必要な概念の解説を行う予定である．受講生が研究などでクラウドを利用する際の，足がかりとなることができればこの講義の目的は十分達成されたことになる．

講義スケジュールは以下の通りである．

[cols="1,2,2", options="header"] 
.講義スケジュール
|===
| | 講義 | ハンズオン
| 第一回 (6/24) | クラウドの基礎 | AWSに自分のサーバーを立ち上げてみる
| 第二回 (7/1) | クラウドを使った科学計算 | AWSで機械学習をやってみる
| 第三回 (7/8) | Serverless Architecture 入門 | AWSでデータベースを作ってみる
|===

第一回：講義初回は，クラウドの基礎となる概念・知識を解説する．セキュリティやネットワークなど，クラウドを利用する上で最低限おさえなければいけないポイントを紹介する．ハンズオンでは，自分のサーバーをAWSに立ち上げる方法を紹介する．

第二回：第二回では，クラウド上で科学計算を走らせるための手法を紹介する．併せて，
https://www.docker.com/[Docker]
とよばれる仮想計算環境に自分のプログラムをパッケージングする手順を説明する．ハンズオンでは，AWSのクラウドでJupyter notebookを使って簡単な機械学習の計算を走らせる課題を実践する．

第三回：第三回では，Serverless architectureと呼ばれる最新のクラウドのアーキテクチャを紹介する．これは，サーバーの処理能力を負荷に応じてより柔軟に拡大・縮小するための概念であり，それ以前(Serverfullとしばしば呼ばれる)と質的に異なる設計思想をクラウドに導入するものである．これの実践として，ハンズオンでは簡単なデータベースをクラウド上に作成する．

[[environments]]
=== 必要な計算機環境

講義では，AWS上にクラウドを展開するハンズオンを実施する．そこで紹介するプログラムを実行するため，以下の計算機環境が必要である．

- **UNIX系コンソール**: ハンズオンで紹介するコマンドを実行したり，SSHでサーバーにアクセスするため，UNIX系のコンソール環境が必要である．Mac または Linux のユーザーは，OSに標準搭載のコンソールを使用すればよい．Windowsのユーザーは，
https://docs.microsoft.com/en-us/windows/wsl/install-win10[Windows Subsystem for Linux (WSL)]
を使ってUbuntuの仮想環境をインストールすることを推奨する．
WSLのインストールについては，
https://docs.microsoft.com/en-us/windows/wsl/install-win10[公式ドキュメンテーションを参照]
のこと．
- **Dockerのインストール**: 講義ではDockerの使い方を解説する．予め自身の計算機にDockerのインストールをしておくとこと．Linux/Mac/Windowsのインストール法については https://docs.docker.com/get-docker/[公式ドキュメンテーション]を参照．執筆時点において，**Windows 10 Home**へのインストールには注意が必要である．詳細は
https://docs.docker.com/docker-for-windows/install-windows-home/[こちらのドキュメンテーションを参照]
のこと．
- **Python** (Version 3.6以上推奨)
- **node.js** (version 10.0以上推奨)

=== 前提知識

本講義を行うにあたり，前提知識は特に仮定しない．が，以下の前提知識があるとよりスムーズに理解をすることができるだろう．

- **Pythonの基本的な理解**: 本講義ではPythonを使ってプログラムの作成を行う．使用するライブラリは十分抽象化されており，関数の名前を見ただけで意味が明瞭なものがほとんどであるので，Pythonに詳しくなくても心配はない．
- **Linuxコマンドラインの基礎的な理解**: クラウドを利用する際，クラウド上に立ち上がるサーバーは基本的にLinuxである(Windowsを選択することもできなくはないが一般的ではない)．Linuxのコマンドラインについて知識があると，トラブルシュートなどが容易になる．

[[aws_account]]
=== AWSアカウント

本講義のハンズオンを実行するにあたり，個人のAWSアカウントの取得が必要である．

AWSには無料利用枠(Free tier)というものがあり，少量の計算であれば無料で行える (https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc[詳細])．講義のハンズオンではなるべく無料枠内で完結できるよう努めるが，場合によっては多少のコストが発生する可能性がある点はご承知いただきたい．

また，
https://aws.amazon.com/education/awseducate/[AWS Educate]
を介してアカウントを作成すれば，$30分の利用クーポンが手に入るので(2020/05時点)，ぜひ利用していただきたい．

[NOTE]
====
AWS Educate の登録手順についてはAppendixに記載してある．
====

=== 講義に関連する資料

ハンズオンで使うプログラム，および教科書とそのソースコードは以下のGitLabで公開している．

https://gitlab.com/tomomano/intro-aws

=== 本書で使用するノーテーションなど

* プログラムのコードやシェルのコマンドは `monospace letter` で記述する．
* シェルに入力するコマンドは，それがシェルコマンドであると明示する目的で，先頭に `$` がつけてある． `$` はコマンドをコピー&ペーストするときは除かなければならない．

また，以下のような形式で注意やチップスを提供する．

NOTE: 追加のコメントなどを記す．

TIP: 発展的な議論やアイディアなどを紹介する．

WARNING: 陥りやすいミスなどの注意事項を述べる．

IMPORTANT: 絶対に犯してはならないミスを指摘する．


.もっと勉強したい人へ
****
クラウドの実践的な教材としては，以下のリソースが役に立つだろう．

- https://aws.amazon.com/education/awseducate/[AWS Educate]
(AWSが公式で提供している学生向けのクラウド学習教材．オンラインの教科書・動画・コーディングなどで学べる．学生ならば受講は無料．)
- https://docs.aws.amazon.com/[AWS公式ドキュメント]
(クラウド技術は日進月歩であり，新しい機能やサービスが毎年のように更新され，昔の情報はどんどん古くなっていく．公式ドキュメンテーションで常に最新の情報を参照すべし．)

また，クラウドというのは様々な情報技術の総体である．クラウドのインフラを支える理論について興味がある場合は，ネットワーク・OS・データベースなど，個別のテーマに絞った本を参照することをおすすめする．
****
